# Generated by Django 6.0.1 on 2026-01-07 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_consulta_hospital(apps, schema_editor):
    Consulta = apps.get_model("core", "Consulta")
    for consulta in Consulta.objects.select_related("paciente"):
        if consulta.paciente_id and consulta.paciente.hospital_id:
            consulta.hospital_id = consulta.paciente.hospital_id
            consulta.save(update_fields=["hospital"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_consulta"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="hospital",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.hospital",
            ),
        ),
        migrations.RunPython(populate_consulta_hospital, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="consulta",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.hospital",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=100)),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("hospital", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.hospital")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Receita",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("RASCUNHO", "Rascunho"), ("ASSINADA", "Assinada")], default="RASCUNHO", max_length=20)),
                ("json_content", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("consulta", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="receitas", to="core.consulta")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("hospital", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.hospital")),
            ],
        ),
        migrations.CreateModel(
            name="Observacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("texto", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("consulta", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="observacoes", to="core.consulta")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("hospital", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.hospital")),
            ],
        ),
    ]
