# Generated by Django 6.0.1 on 2026-01-07 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tenant_and_receitas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="cpf",
            field=models.CharField(max_length=14),
        ),
        migrations.AddConstraint(
            model_name="paciente",
            constraint=models.UniqueConstraint(fields=("hospital", "cpf"), name="unique_cpf_por_hospital"),
        ),
        migrations.AddConstraint(
            model_name="usuario",
            constraint=models.UniqueConstraint(fields=("hospital", "email"), name="unique_email_por_hospital"),
        ),
        migrations.AddIndex(
            model_name="paciente",
            index=models.Index(fields=["hospital"], name="core_pacien_hospital_idx"),
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(fields=["hospital"], name="core_consul_hospital_idx"),
        ),
        migrations.AddIndex(
            model_name="receita",
            index=models.Index(fields=["hospital"], name="core_receit_hospital_idx"),
        ),
        migrations.AddIndex(
            model_name="observacao",
            index=models.Index(fields=["hospital"], name="core_observ_hospital_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["hospital"], name="core_auditl_hospital_idx"),
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("versao", models.PositiveIntegerField()),
                ("conteudo", models.TextField()),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hospital", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.hospital")),
            ],
        ),
        migrations.CreateModel(
            name="HospitalKnowledgeItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(max_length=100)),
                ("texto", models.TextField()),
                ("versao", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("aprovado_por", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("hospital", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.hospital")),
            ],
        ),
        migrations.CreateModel(
            name="AiDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("input_sem_pii", models.JSONField()),
                ("output_json", models.JSONField()),
                ("modelo", models.CharField(max_length=50)),
                ("prompt_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("consulta", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.consulta")),
                ("hospital", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.hospital")),
            ],
        ),
        migrations.CreateModel(
            name="AiFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.PositiveIntegerField()),
                ("motivo", models.TextField(blank=True)),
                ("correcoes_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("draft", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.aidraft")),
                ("hospital", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.hospital")),
                ("medico", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="BulaCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("url_pdf", models.URLField(blank=True, null=True)),
                ("conteudo", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hospital", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.hospital")),
            ],
        ),
        migrations.CreateModel(
            name="BulaAccessLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField()),
                ("titulo", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hospital", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.hospital")),
            ],
        ),
        migrations.AddIndex(
            model_name="prompttemplate",
            index=models.Index(fields=["hospital"], name="core_prompt_hospital_idx"),
        ),
        migrations.AddIndex(
            model_name="hospitalknowledgeitem",
            index=models.Index(fields=["hospital"], name="core_hospit_hospital_idx"),
        ),
        migrations.AddIndex(
            model_name="aidraft",
            index=models.Index(fields=["hospital"], name="core_aidra_hospital_idx"),
        ),
        migrations.AddIndex(
            model_name="aifeedback",
            index=models.Index(fields=["hospital"], name="core_aifee_hospital_idx"),
        ),
        migrations.AddIndex(
            model_name="bulacache",
            index=models.Index(fields=["hospital"], name="core_bulac_hospital_idx"),
        ),
        migrations.AddIndex(
            model_name="bulaaccesslog",
            index=models.Index(fields=["hospital"], name="core_bulaa_hospital_idx"),
        ),
    ]
