# Generated by Django 6.0.1 on 2026-01-08 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_learning_loop_and_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=20)),
                ('uf_crm', models.CharField(default='SP', max_length=2)),
                ('assinatura_img', models.ImageField(blank=True, null=True, upload_to='assinaturas/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='historico_clinico',
            new_name='historico_alergias',
        ),
        migrations.RenameIndex(
            model_name='aidraft',
            new_name='core_aidraf_hospita_c89388_idx',
            old_name='core_aidra_hospital_idx',
        ),
        migrations.RenameIndex(
            model_name='aifeedback',
            new_name='core_aifeed_hospita_62c991_idx',
            old_name='core_aifee_hospital_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_hospita_d95c26_idx',
            old_name='core_auditl_hospital_idx',
        ),
        migrations.RenameIndex(
            model_name='bulaaccesslog',
            new_name='core_bulaac_hospita_b0d0f1_idx',
            old_name='core_bulaa_hospital_idx',
        ),
        migrations.RenameIndex(
            model_name='bulacache',
            new_name='core_bulaca_hospita_c45a47_idx',
            old_name='core_bulac_hospital_idx',
        ),
        migrations.RenameIndex(
            model_name='consulta',
            new_name='core_consul_hospita_a626cc_idx',
            old_name='core_consul_hospital_idx',
        ),
        migrations.RenameIndex(
            model_name='hospitalknowledgeitem',
            new_name='core_hospit_hospita_77cbc9_idx',
            old_name='core_hospit_hospital_idx',
        ),
        migrations.RenameIndex(
            model_name='observacao',
            new_name='core_observ_hospita_5aae1a_idx',
            old_name='core_observ_hospital_idx',
        ),
        migrations.RenameIndex(
            model_name='paciente',
            new_name='core_pacien_hospita_e455e2_idx',
            old_name='core_pacien_hospital_idx',
        ),
        migrations.RenameIndex(
            model_name='prompttemplate',
            new_name='core_prompt_hospita_87d428_idx',
            old_name='core_prompt_hospital_idx',
        ),
        migrations.RenameIndex(
            model_name='receita',
            new_name='core_receit_hospita_3f4d24_idx',
            old_name='core_receit_hospital_idx',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medico_responsavel',
        ),
        migrations.AddField(
            model_name='hospital',
            name='admin_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitais_geridos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospital',
            name='cor_primaria',
            field=models.CharField(default='#2c3e50', help_text='Código Hex da cor (ex: #000000)', max_length=7),
        ),
        migrations.AddField(
            model_name='hospital',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_hospitais/'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='analise_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='cnpj',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_completo',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='perfilmedico',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital'),
        ),
        migrations.AddField(
            model_name='perfilmedico',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_medico', to=settings.AUTH_USER_MODEL),
        ),
    ]
